default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  host: localhost
  port: 3306

development:
  <<: *default
  database: seisan_keikaku_2_development

test:
  <<: *default
  database: seisan_keikaku_2_test

production:
  <<: *default
  database: seisan_keikaku_2_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
